<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Project-so-far</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Project-so-far_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project-so-far_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Project-so-far_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Project-so-far_files/libs/quarto-html/popper.min.js"></script>
<script src="Project-so-far_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project-so-far_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project-so-far_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project-so-far_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project-so-far_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project-so-far_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project-so-far_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project-so-far</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The data</h2>
<p>The data set I chose is the <a href="https://www.kaggle.com/datasets/algozee/teenager-menthal-healy/data">Social Media Impact on Teen Mental Health</a> data set. This data studies how social media use affects the mental health of teenagers. It includes daily habits like social media hours, sleep, stress, anxiety, and physical activity. I chose this data because of the normalization of what people are calling “doom scrolling,” which in lammens terms is spending hours scrolling through social media with no end in sight. Most social media platforms today all have a section for short, repeating clips and videos that are meant to hold your attention for hours on end. I myself have caught myself doom scrolling, losing track of time and becoming completely encapsulated by these short videos, often called “shorts.” What I want to know is whether or not spending large amounts of time on social media can influence your mental health, and whether other daily activities such as exercise, sleep, and real-life interactions can benefit mental health.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>TMH <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Teen_Mental_Health_Dataset.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1200 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): gender, platform_usage, social_interaction_level
dbl (10): age, daily_social_media_hours, sleep_hours, screen_time_before_sle...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(TMH)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age              gender     daily_social_media_hours   platform_usage
 Min.   :13.00   Length   :1200   Min.   :1.000            Length   :1200  
 1st Qu.:14.00   N.unique :   2   1st Qu.:2.800            N.unique :   3  
 Median :16.00   N.blank  :   0   Median :4.500            N.blank  :   0  
 Mean   :15.93   Min.nchar:   4   Mean   :4.537            Min.nchar:   4  
 3rd Qu.:18.00   Max.nchar:   6   3rd Qu.:6.300            Max.nchar:   9  
 Max.   :19.00                    Max.   :8.000                            
  sleep_hours    screen_time_before_sleep academic_performance
 Min.   :4.000   Min.   :0.50             Min.   :2.00        
 1st Qu.:5.200   1st Qu.:1.10             1st Qu.:2.50        
 Median :6.500   Median :1.80             Median :2.99        
 Mean   :6.449   Mean   :1.74             Mean   :2.99        
 3rd Qu.:7.600   3rd Qu.:2.40             3rd Qu.:3.48        
 Max.   :9.000   Max.   :3.00             Max.   :4.00        
 physical_activity social_interaction_level  stress_level    anxiety_level   
 Min.   :0.000     Length   :1200           Min.   : 1.000   Min.   : 1.000  
 1st Qu.:0.500     N.unique :   3           1st Qu.: 3.000   1st Qu.: 3.000  
 Median :1.000     N.blank  :   0           Median : 5.000   Median : 6.000  
 Mean   :1.014     Min.nchar:   3           Mean   : 5.446   Mean   : 5.637  
 3rd Qu.:1.500     Max.nchar:   6           3rd Qu.: 8.000   3rd Qu.: 8.000  
 Max.   :2.000                              Max.   :10.000   Max.   :10.000  
 addiction_level  depression_label 
 Min.   : 1.000   Min.   :0.00000  
 1st Qu.: 3.000   1st Qu.:0.00000  
 Median : 6.000   Median :0.00000  
 Mean   : 5.565   Mean   :0.02583  
 3rd Qu.: 8.000   3rd Qu.:0.00000  
 Max.   :10.000   Max.   :1.00000  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(TMH)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,200 × 13] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ age                     : num [1:1200] 14 19 17 15 15 19 18 16 19 15 ...
 $ gender                  : chr [1:1200] "male" "female" "female" "male" ...
 $ daily_social_media_hours: num [1:1200] 7.9 1.9 1.3 7.4 4.7 7.4 2.5 4 3.3 1.9 ...
 $ platform_usage          : chr [1:1200] "Instagram" "TikTok" "Instagram" "TikTok" ...
 $ sleep_hours             : num [1:1200] 7.4 8 7.6 6.9 4.9 4.4 6.4 4.2 5 4.9 ...
 $ screen_time_before_sleep: num [1:1200] 2.9 2.9 0.5 1.6 3 2.4 2.4 0.5 2.1 1.5 ...
 $ academic_performance    : num [1:1200] 3.01 3.22 3.92 3.48 2.37 2.63 2.63 2.4 2.04 3.77 ...
 $ physical_activity       : num [1:1200] 1.5 0.8 0 0.8 1.4 0.6 0.7 1.3 0.9 1.1 ...
 $ social_interaction_level: chr [1:1200] "low" "high" "high" "medium" ...
 $ stress_level            : num [1:1200] 2 8 2 1 3 3 2 6 1 1 ...
 $ anxiety_level           : num [1:1200] 2 1 4 7 5 5 2 10 10 1 ...
 $ addiction_level         : num [1:1200] 1 10 2 9 2 7 5 5 9 4 ...
 $ depression_label        : num [1:1200] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "spec")=
  .. cols(
  ..   age = col_double(),
  ..   gender = col_character(),
  ..   daily_social_media_hours = col_double(),
  ..   platform_usage = col_character(),
  ..   sleep_hours = col_double(),
  ..   screen_time_before_sleep = col_double(),
  ..   academic_performance = col_double(),
  ..   physical_activity = col_double(),
  ..   social_interaction_level = col_character(),
  ..   stress_level = col_double(),
  ..   anxiety_level = col_double(),
  ..   addiction_level = col_double(),
  ..   depression_label = col_double()
  .. )
 - attr(*, "problems")=&lt;pointer: 0x962ff00a0&gt; </code></pre>
</div>
</div>
<p>Lets change some of the character values to factors. I also will not be including <code>addiction level</code> nor <code>platform_ usage</code> in this model. I won’t be including <code>addiction level</code> because it is too closely related to the response variable of interest, <code>depression label</code> (a binary variable taking on values 0 or 1). I won’t be including <code>platform_ usage</code> because it doesn’t relate to our research question. If we wanted to measure which platforms are more closely related to depression, then we’d include it. What we’re interested in though, is how <strong>all</strong> social media usage affects teen mental health.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>TMH<span class="sc">$</span>gender <span class="ot">&lt;-</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(TMH<span class="sc">$</span>gender,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"female"</span>, <span class="st">"male"</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>TMH<span class="sc">$</span>social_interaction_level <span class="ot">&lt;-</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(TMH<span class="sc">$</span>social_interaction_level,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"medium"</span>, <span class="st">"high"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Lets check the model for multicolinearity. We’ll do this by checking the correlation between all of our numeric predictors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(TMH[, <span class="fu">c</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"age"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"daily_social_media_hours"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sleep_hours"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"screen_time_before_sleep"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"academic_performance"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"physical_activity"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"stress_level"</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  age daily_social_media_hours  sleep_hours
age                       1.000000000             -0.006634980  0.001529615
daily_social_media_hours -0.006634980              1.000000000 -0.009472174
sleep_hours               0.001529615             -0.009472174  1.000000000
screen_time_before_sleep  0.075611831              0.035777475  0.010235281
academic_performance     -0.013972572              0.013178979  0.021866484
physical_activity         0.011086166              0.025545976  0.012700669
stress_level             -0.031208171              0.030697742 -0.010979224
                         screen_time_before_sleep academic_performance
age                                   0.075611831        -0.0139725717
daily_social_media_hours              0.035777475         0.0131789791
sleep_hours                           0.010235281         0.0218664840
screen_time_before_sleep              1.000000000        -0.0347150611
academic_performance                 -0.034715061         1.0000000000
physical_activity                    -0.026450022         0.0233118328
stress_level                         -0.008649586        -0.0006002253
                         physical_activity  stress_level
age                             0.01108617 -0.0312081715
daily_social_media_hours        0.02554598  0.0306977419
sleep_hours                     0.01270067 -0.0109792243
screen_time_before_sleep       -0.02645002 -0.0086495864
academic_performance            0.02331183 -0.0006002253
physical_activity               1.00000000  0.0121594672
stress_level                    0.01215947  1.0000000000</code></pre>
</div>
</div>
<p>The correlations are all below 0.08, so none of our numeric predictors are strongly correlated with each other. That means there is no evidence of multicollinearity based on these pairwise correlations</p>
</section>
<section id="model-selection" class="level2">
<h2 class="anchored" data-anchor-id="model-selection">Model selection</h2>
<p>Before we decide on a model, lets fit the full model and see which variables are significant based on their p-values. We’ll use a significance level of 0.05 for this model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  depression_label <span class="sc">~</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    age <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    gender <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    daily_social_media_hours <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    sleep_hours <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    screen_time_before_sleep <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    academic_performance <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    physical_activity <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    social_interaction_level <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    stress_level <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    anxiety_level,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> TMH,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
</div>
<p>When fitting this model, we get the following warning: “Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred.” It means one or more combinations of predictors almost perfectly predict the outcome. The first thing we’ll do is not remove variables yet. Instead, let’s see what’s causing the warning by running <code>summary(full_model)</code> and <code>range(fitted(full_model))</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = depression_label ~ age + gender + daily_social_media_hours + 
    sleep_hours + screen_time_before_sleep + academic_performance + 
    physical_activity + social_interaction_level + stress_level + 
    anxiety_level, family = binomial(link = "logit"), data = TMH)

Coefficients:
                               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                    -15.7959     4.6513  -3.396 0.000684 ***
age                              0.1386     0.1496   0.926 0.354279    
gendermale                      -1.4143     0.6919  -2.044 0.040942 *  
daily_social_media_hours         1.1764     0.2294   5.129 2.92e-07 ***
sleep_hours                     -2.5059     0.4985  -5.027 4.98e-07 ***
screen_time_before_sleep        -0.5980     0.4048  -1.477 0.139576    
academic_performance             1.0395     0.5872   1.770 0.076673 .  
physical_activity               -0.8514     0.5793  -1.470 0.141639    
social_interaction_levelmedium   0.4710     0.7781   0.605 0.544942    
social_interaction_levelhigh     0.2768     0.7868   0.352 0.724942    
stress_level                     0.9502     0.1893   5.021 5.15e-07 ***
anxiety_level                    1.1075     0.2315   4.783 1.73e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 287.870  on 1199  degrees of freedom
Residual deviance:  79.451  on 1188  degrees of freedom
AIC: 103.45

Number of Fisher Scoring iterations: 10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(<span class="fu">fitted</span>(full_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.220446e-16 9.985867e-01</code></pre>
</div>
</div>
<p>Running <code>range(fitted(full_model))</code> gave us <span class="math inline">\(2.22*10^{-16}\)</span> to <span class="math inline">\(0.9986\)</span>, which confirms there are observations that the model predicts with almost complete certainty. Since all the coefficient estimates and standard errors are finite, this is not complete separation—it’s more likely quasi-complete separation. For this project, I don’t think it’s a major concern, but we should mention it briefly in the report.</p>
<p>Based on the summary of the model,</p>
<section id="variables-i-would-definitely-keep" class="level3">
<h3 class="anchored" data-anchor-id="variables-i-would-definitely-keep">Variables I would definitely keep</h3>
<p>These are statistically significant and have clear interpretations:</p>
<ul>
<li><p><code>gender</code> (p = 0.041)</p></li>
<li><p><code>daily_social_media_hours</code> (p &lt; 0.001)</p></li>
<li><p><code>sleep_hours</code> (p &lt; 0.001)</p></li>
<li><p><code>stress_level</code> (p &lt; 0.001)</p></li>
<li><p><code>anxiety_level</code> (p &lt; 0.001)</p></li>
</ul>
</section>
<section id="variables-to-consider-removing" class="level3">
<h3 class="anchored" data-anchor-id="variables-to-consider-removing">Variables to consider removing</h3>
<p>These do not appear to contribute much once the other variables are in the model:</p>
<ul>
<li><p><code>age</code> (p = 0.354)</p></li>
<li><p><code>screen_time_before_sleep</code> (p = 0.140)</p></li>
<li><p><code>physical_activity</code> (p = 0.142)</p></li>
<li><p><code>social_interaction_level</code> (both levels p &gt; 0.5)</p></li>
</ul>
</section>
<section id="one-variable-id-think-about" class="level3">
<h3 class="anchored" data-anchor-id="one-variable-id-think-about">One variable I’d think about</h3>
<ul>
<li><p><code>academic_performance</code></p>
<ul>
<li><p>p = 0.077</p></li>
<li><p>It’s close to the 0.05 level.</p></li>
<li><p>I’ll keep it for one more model to see whether it becomes significant after removing clearly unimportant variables</p></li>
</ul></li>
</ul>
<p>Lets fit another model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>reduced_model_1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  depression_label <span class="sc">~</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    gender <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    daily_social_media_hours <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    sleep_hours <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    academic_performance <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    stress_level <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    anxiety_level,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> TMH,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reduced_model_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = depression_label ~ gender + daily_social_media_hours + 
    sleep_hours + academic_performance + stress_level + anxiety_level, 
    family = binomial(link = "logit"), data = TMH)

Coefficients:
                         Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -13.4346     3.1333  -4.288 1.81e-05 ***
gendermale                -1.3626     0.6479  -2.103   0.0354 *  
daily_social_media_hours   1.1029     0.2176   5.069 4.00e-07 ***
sleep_hours               -2.3297     0.4493  -5.185 2.16e-07 ***
academic_performance       0.7817     0.5252   1.488   0.1367    
stress_level               0.8833     0.1770   4.991 6.00e-07 ***
anxiety_level              0.9982     0.2018   4.948 7.51e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 287.870  on 1199  degrees of freedom
Residual deviance:  86.072  on 1193  degrees of freedom
AIC: 100.07

Number of Fisher Scoring iterations: 10</code></pre>
</div>
</div>
<p>This model showed an improvement in Akaike’s Information Criterion (AIC). The <code>full_model</code> had an AIC of 103.45, compared to an AIC of 100.07 from <code>reduced_model_1</code>.</p>
<p>However, <code>academic_performance</code> now has a p-value of 0.14, which is no longer close to significance. Lets remove it and look at the difference.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>reduced_model_2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  depression_label <span class="sc">~</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    gender <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    daily_social_media_hours <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    sleep_hours <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    stress_level <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    anxiety_level,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> TMH,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reduced_model_2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = depression_label ~ gender + daily_social_media_hours + 
    sleep_hours + stress_level + anxiety_level, family = binomial(link = "logit"), 
    data = TMH)

Coefficients:
                         Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -11.2965     2.6575  -4.251 2.13e-05 ***
gendermale                -1.3701     0.6376  -2.149   0.0316 *  
daily_social_media_hours   1.1423     0.2198   5.197 2.03e-07 ***
sleep_hours               -2.2489     0.4308  -5.220 1.79e-07 ***
stress_level               0.8718     0.1711   5.094 3.51e-07 ***
anxiety_level              0.9492     0.1963   4.836 1.32e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 287.870  on 1199  degrees of freedom
Residual deviance:  88.334  on 1194  degrees of freedom
AIC: 100.33

Number of Fisher Scoring iterations: 10</code></pre>
</div>
</div>
<p>Hold up. <code>reduced_model_1</code> actually has the lower AIC, even though it includes one additional predictor (<code>academic_performance</code>) that isn’t individually significant.</p>
</section>
<section id="what-does-this-mean" class="level3">
<h3 class="anchored" data-anchor-id="what-does-this-mean">What does this mean?</h3>
<p>Removing <code>academic_performance</code> made the model:</p>
<ul>
<li><p>slightly simpler,</p></li>
<li><p>but it <strong>didn’t improve the overall fit</strong>. In fact, the AIC got a little worse</p></li>
</ul>
<p>For this project, we will use <code>reduced_model_1</code> because</p>
<ul>
<li><p>It has the <strong>lowest AIC</strong> of all the models we fit.</p></li>
<li><p><code>academic_performance</code> is close enough to significance that it’s reasonable to retain.</p></li>
<li><p>It adds only one coefficient, so we’re not sacrificing much simplicity.</p></li>
<li><p>It lets us discuss that academic performance may contribute to depression after controlling for the other variables, even if the evidence isn’t quite strong enough to declare it statistically significant at the 0.05 level.</p></li>
</ul>
</section>
</section>
<section id="recap-of-model-selection" class="level2">
<h2 class="anchored" data-anchor-id="recap-of-model-selection">Recap of model selection</h2>
<p>We began by fitting a logistic regression model containing all plausible explanatory variables. Variables that were not statistically significant were removed sequentially, and competing models were compared using Akaike’s Information Criterion (AIC). The final model was chosen based on a balance between model fit, parsimony, and interpretability. Although academic performance was not statistically significant at the 5% level, retaining it produced the lowest AIC of 100.07, so it was included in the final model</p>
<p>Lets store our final model into an object called <code>final_model</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>final_model <span class="ot">&lt;-</span> reduced_model_1</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(final_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = depression_label ~ gender + daily_social_media_hours + 
    sleep_hours + academic_performance + stress_level + anxiety_level, 
    family = binomial(link = "logit"), data = TMH)

Coefficients:
                         Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)              -13.4346     3.1333  -4.288 1.81e-05 ***
gendermale                -1.3626     0.6479  -2.103   0.0354 *  
daily_social_media_hours   1.1029     0.2176   5.069 4.00e-07 ***
sleep_hours               -2.3297     0.4493  -5.185 2.16e-07 ***
academic_performance       0.7817     0.5252   1.488   0.1367    
stress_level               0.8833     0.1770   4.991 6.00e-07 ***
anxiety_level              0.9982     0.2018   4.948 7.51e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 287.870  on 1199  degrees of freedom
Residual deviance:  86.072  on 1193  degrees of freedom
AIC: 100.07

Number of Fisher Scoring iterations: 10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(final_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 30
 $ coefficients     : Named num [1:7] -13.435 -1.363 1.103 -2.33 0.782 ...
  ..- attr(*, "names")= chr [1:7] "(Intercept)" "gendermale" "daily_social_media_hours" "sleep_hours" ...
 $ residuals        : Named num [1:1200] -1 -1 -1 -1 -1 ...
  ..- attr(*, "names")= chr [1:1200] "1" "2" "3" "4" ...
 $ fitted.values    : Named num [1:1200] 3.36e-08 3.77e-09 8.52e-10 5.45e-06 3.82e-05 ...
  ..- attr(*, "names")= chr [1:1200] "1" "2" "3" "4" ...
 $ effects          : Named num [1:1200] 3.892 0.403 2.448 2.083 0.275 ...
  ..- attr(*, "names")= chr [1:1200] "(Intercept)" "gendermale" "daily_social_media_hours" "sleep_hours" ...
 $ R                : num [1:7, 1:7] -3.52 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:7] "(Intercept)" "gendermale" "daily_social_media_hours" "sleep_hours" ...
  .. ..$ : chr [1:7] "(Intercept)" "gendermale" "daily_social_media_hours" "sleep_hours" ...
 $ rank             : int 7
 $ qr               :List of 5
  ..$ qr   : num [1:1200, 1:7] -3.52 1.75e-05 8.30e-06 6.64e-04 1.76e-03 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:1200] "1" "2" "3" "4" ...
  .. .. ..$ : chr [1:7] "(Intercept)" "gendermale" "daily_social_media_hours" "sleep_hours" ...
  ..$ rank : int 7
  ..$ qraux: num [1:7] 1 1 1 1 1 ...
  ..$ pivot: int [1:7] 1 2 3 4 5 6 7
  ..$ tol  : num 1e-11
  ..- attr(*, "class")= chr "qr"
 $ family           :List of 13
  ..$ family    : chr "binomial"
  ..$ link      : chr "logit"
  ..$ linkfun   :function (mu)  
  ..$ linkinv   :function (eta)  
  ..$ variance  :function (mu)  
  ..$ dev.resids:function (y, mu, wt)  
  ..$ aic       :function (y, n, mu, wt, dev)  
  ..$ mu.eta    :function (eta)  
  ..$ initialize: language {     if (NCOL(y) == 1) { ...
  ..$ validmu   :function (mu)  
  ..$ valideta  :function (eta)  
  ..$ simulate  :function (object, nsim)  
  ..$ dispersion: num 1
  ..- attr(*, "class")= chr "family"
 $ linear.predictors: Named num [1:1200] -17.2 -19.4 -20.9 -12.1 -10.2 ...
  ..- attr(*, "names")= chr [1:1200] "1" "2" "3" "4" ...
 $ deviance         : num 86.1
 $ aic              : num 100
 $ null.deviance    : num 288
 $ iter             : int 10
 $ weights          : Named num [1:1200] 3.36e-08 3.77e-09 8.53e-10 5.45e-06 3.82e-05 ...
  ..- attr(*, "names")= chr [1:1200] "1" "2" "3" "4" ...
 $ prior.weights    : Named num [1:1200] 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "names")= chr [1:1200] "1" "2" "3" "4" ...
 $ df.residual      : int 1193
 $ df.null          : int 1199
 $ y                : Named num [1:1200] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "names")= chr [1:1200] "1" "2" "3" "4" ...
 $ converged        : logi TRUE
 $ boundary         : logi FALSE
 $ model            :'data.frame':  1200 obs. of  7 variables:
  ..$ depression_label        : num [1:1200] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ gender                  : Factor w/ 2 levels "female","male": 2 1 1 2 1 1 1 2 1 2 ...
  ..$ daily_social_media_hours: num [1:1200] 7.9 1.9 1.3 7.4 4.7 7.4 2.5 4 3.3 1.9 ...
  ..$ sleep_hours             : num [1:1200] 7.4 8 7.6 6.9 4.9 4.4 6.4 4.2 5 4.9 ...
  ..$ academic_performance    : num [1:1200] 3.01 3.22 3.92 3.48 2.37 2.63 2.63 2.4 2.04 3.77 ...
  ..$ stress_level            : num [1:1200] 2 8 2 1 3 3 2 6 1 1 ...
  ..$ anxiety_level           : num [1:1200] 2 1 4 7 5 5 2 10 10 1 ...
  ..- attr(*, "terms")=Classes 'terms', 'formula'  language depression_label ~ gender + daily_social_media_hours + sleep_hours + academic_performance +      stress_level + anxiety_level
  .. .. ..- attr(*, "variables")= language list(depression_label, gender, daily_social_media_hours, sleep_hours, academic_performance,      stress_level, anxiety_level)
  .. .. ..- attr(*, "factors")= int [1:7, 1:6] 0 1 0 0 0 0 0 0 0 1 ...
  .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. ..$ : chr [1:7] "depression_label" "gender" "daily_social_media_hours" "sleep_hours" ...
  .. .. .. .. ..$ : chr [1:6] "gender" "daily_social_media_hours" "sleep_hours" "academic_performance" ...
  .. .. ..- attr(*, "term.labels")= chr [1:6] "gender" "daily_social_media_hours" "sleep_hours" "academic_performance" ...
  .. .. ..- attr(*, "order")= int [1:6] 1 1 1 1 1 1
  .. .. ..- attr(*, "intercept")= int 1
  .. .. ..- attr(*, "response")= int 1
  .. .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
  .. .. ..- attr(*, "predvars")= language list(depression_label, gender, daily_social_media_hours, sleep_hours, academic_performance,      stress_level, anxiety_level)
  .. .. ..- attr(*, "dataClasses")= Named chr [1:7] "numeric" "factor" "numeric" "numeric" ...
  .. .. .. ..- attr(*, "names")= chr [1:7] "depression_label" "gender" "daily_social_media_hours" "sleep_hours" ...
 $ call             : language glm(formula = depression_label ~ gender + daily_social_media_hours + sleep_hours +      academic_performance + st| __truncated__ ...
 $ formula          :Class 'formula'  language depression_label ~ gender + daily_social_media_hours + sleep_hours + academic_performance +      stress_level + anxiety_level
  .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
 $ terms            :Classes 'terms', 'formula'  language depression_label ~ gender + daily_social_media_hours + sleep_hours + academic_performance +      stress_level + anxiety_level
  .. ..- attr(*, "variables")= language list(depression_label, gender, daily_social_media_hours, sleep_hours, academic_performance,      stress_level, anxiety_level)
  .. ..- attr(*, "factors")= int [1:7, 1:6] 0 1 0 0 0 0 0 0 0 1 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:7] "depression_label" "gender" "daily_social_media_hours" "sleep_hours" ...
  .. .. .. ..$ : chr [1:6] "gender" "daily_social_media_hours" "sleep_hours" "academic_performance" ...
  .. ..- attr(*, "term.labels")= chr [1:6] "gender" "daily_social_media_hours" "sleep_hours" "academic_performance" ...
  .. ..- attr(*, "order")= int [1:6] 1 1 1 1 1 1
  .. ..- attr(*, "intercept")= int 1
  .. ..- attr(*, "response")= int 1
  .. ..- attr(*, ".Environment")=&lt;environment: R_GlobalEnv&gt; 
  .. ..- attr(*, "predvars")= language list(depression_label, gender, daily_social_media_hours, sleep_hours, academic_performance,      stress_level, anxiety_level)
  .. ..- attr(*, "dataClasses")= Named chr [1:7] "numeric" "factor" "numeric" "numeric" ...
  .. .. ..- attr(*, "names")= chr [1:7] "depression_label" "gender" "daily_social_media_hours" "sleep_hours" ...
 $ data             : spc_tbl_ [1,200 × 13] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
  ..$ age                     : num [1:1200] 14 19 17 15 15 19 18 16 19 15 ...
  ..$ gender                  : Factor w/ 2 levels "female","male": 2 1 1 2 1 1 1 2 1 2 ...
  ..$ daily_social_media_hours: num [1:1200] 7.9 1.9 1.3 7.4 4.7 7.4 2.5 4 3.3 1.9 ...
  ..$ platform_usage          : chr [1:1200] "Instagram" "TikTok" "Instagram" "TikTok" ...
  ..$ sleep_hours             : num [1:1200] 7.4 8 7.6 6.9 4.9 4.4 6.4 4.2 5 4.9 ...
  ..$ screen_time_before_sleep: num [1:1200] 2.9 2.9 0.5 1.6 3 2.4 2.4 0.5 2.1 1.5 ...
  ..$ academic_performance    : num [1:1200] 3.01 3.22 3.92 3.48 2.37 2.63 2.63 2.4 2.04 3.77 ...
  ..$ physical_activity       : num [1:1200] 1.5 0.8 0 0.8 1.4 0.6 0.7 1.3 0.9 1.1 ...
  ..$ social_interaction_level: Factor w/ 3 levels "low","medium",..: 1 3 3 2 2 3 1 1 3 3 ...
  ..$ stress_level            : num [1:1200] 2 8 2 1 3 3 2 6 1 1 ...
  ..$ anxiety_level           : num [1:1200] 2 1 4 7 5 5 2 10 10 1 ...
  ..$ addiction_level         : num [1:1200] 1 10 2 9 2 7 5 5 9 4 ...
  ..$ depression_label        : num [1:1200] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "spec")=
  .. .. cols(
  .. ..   age = col_double(),
  .. ..   gender = col_character(),
  .. ..   daily_social_media_hours = col_double(),
  .. ..   platform_usage = col_character(),
  .. ..   sleep_hours = col_double(),
  .. ..   screen_time_before_sleep = col_double(),
  .. ..   academic_performance = col_double(),
  .. ..   physical_activity = col_double(),
  .. ..   social_interaction_level = col_character(),
  .. ..   stress_level = col_double(),
  .. ..   anxiety_level = col_double(),
  .. ..   addiction_level = col_double(),
  .. ..   depression_label = col_double()
  .. .. )
  ..- attr(*, "problems")=&lt;pointer: 0x962ff00a0&gt; 
 $ offset           : NULL
 $ control          :List of 3
  ..$ epsilon: num 1e-08
  ..$ maxit  : num 25
  ..$ trace  : logi FALSE
 $ method           : chr "glm.fit"
 $ contrasts        :List of 1
  ..$ gender: chr "contr.treatment"
 $ xlevels          :List of 1
  ..$ gender: chr [1:2] "female" "male"
 - attr(*, "class")= chr [1:2] "glm" "lm"</code></pre>
</div>
</div>
<p>Should we group together some of the numeric variables? Are there any variables I’d consider adding?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(TMH<span class="sc">$</span>daily_social_media_hours))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 71</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>